# Generated by Django 5.2.17 on 2026-09-16 10:33

from django.db import migrations, models

from posthog.migration_helpers import SafeAddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("signals", "0137_signalreport_content_revision_count_and_more"),
    ]

    operations = [
        SafeAddIndexConcurrently(
            model_name="signalreportartefact",
            index=models.Index(
                condition=models.Q(("type", "implementation_replacement")),
                fields=["id"],
                name="signals_replacement_sweep_idx",
            ),
        ),
    ]
